version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: sahil
      POSTGRES_PASSWORD: sahil123
      POSTGRES_DB: gutenberg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sahil -d gutenberg"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sahil:sahil123@db:5432/gutenberg
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data: